name: Build Module

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
    inputs:
      name:
        description: "World"
        default: "Hello"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push modules
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_OWNER: ${{ github.repository_owner }}
      run: |
        for folder in Video Book Text; do
          cd "$folder"
          make build-module
          cp ./*.module /home/runner
          cd ..
        done

        git clone https://github.com/${REPO_OWNER}/${REPO_NAME} built
        cd built
        git checkout built
        for folder in Video Book Text; do
          cp /home/runner/*.module "$folder"/
        done
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update modules"
        git push origin built