name: Build Module
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
    inputs:
      name:
        description: "World"
        default: "Hello"
jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Cloning the repo
      run: |
        git clone https://github.com/$REPO_OWNER/$REPO_NAME && cd $REPO_NAME && git checkout $BRANCH && cd ..
        git clone https://github.com/$REPO_OWNER/$REPO_NAME built && cd built && git checkout built && cd ..
      env: 
        BRANCH:  ${{steps.branch-name.outputs.current_branch}}
        REPO_NAME: ${{github.event.repository.name}}
        REPO_OWNER: ${{github.repository_owner}}
    

    - name: Building the module
      run: |
        cd $REPO_NAME && make build-module && cd ..
        cp $REPO_NAME/*.module ./built/
        cd $REPO_NAME && ls && cd ..
        cd built && ls && cd ..
      env: 
        REPO_NAME: ${{github.event.repository.name}}
        REPO_OWNER: ${{github.repository_owner}}
        TOKEN: ${{secrets.GITHUB_TOKEN}}

    - uses: actions/checkout@v3
      with: 
        ref: "built"
        
    - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cd built && git add . && git commit -m "test" && git push