name: Build Module
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
    inputs:
      name:
        description: "World"
        default: "Hello"
jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Cloning the repo
      run: |
        echo $BRANCH
        echo $REPO_NAME
        echo $REPO_OWNER
      env: 
        BRANCH:  ${{steps.branch-name.outputs.current_branch}}
        REPO_NAME: ${{github.event.repository.name}}
        REPO_OWNER: ${{github.repository_owner}}
